---
title: "HW 1 - Curve fitting to cytotoxicity data"
author: "Lizbeth Gomez & Nastasia Gernat"
date: "2/9/2020"
output: github_document
---
```{r}
library(drc) 
library(tidyverse) 
library(dplyr)
library(janitor) 
library(ggplot2)
library(readxl)
library(raster) 

```

```{r}
cyto_death = read_xlsx("data/cytotox_data.xlsx") %>%
  clean_names() 

summary(cyto_death)



cyto_tidy_death = 
  pivot_longer(
    cyto_death, 
    rep_1:rep_6,
    names_to = "replicates", 
    values_to = "rep")

summary(cyto_tidy_death)

cyto_death_plot <- cyto_tidy_death %>% 
  ggplot(aes(x = concentration, y = rep)) +
  ylim(0, 45) + xlim(0,6) +
  geom_point(aes(color = replicates)) +
  geom_smooth(method= "auto", se= TRUE) 
cyto_death_plot

#Absolute percent cell death per concentration by replication

cyto_death_plot_2 <- cyto_tidy_death %>% 
  ggplot(aes(x = concentration, y = avg_cell_death)) +
  ylim(0, 45) + xlim(0,6) +
  geom_point() +
  geom_smooth(method= "auto", se= TRUE) 
cyto_death_plot_2



#Calculation of percent death from control
cyto_death_plot_3 <- cyto_tidy_death %>% 
  ggplot(aes(x = concentration, y = from_ctr)) +
  ylim(0, 450) + xlim(0,6) +
  geom_point() +
  geom_smooth(method= "auto", se= TRUE) 
cyto_death_plot_3

```

```{r}
cv_mean <- cyto_tidy_death %>%
 group_by(concentration)%>%
  summarise(mean = mean(rep), 
            cv = cv(rep)) %>%
 knitr::kable()
  cv_mean

```

```{r}
regress_cyto<- drm(avg_cell_death ~concentration, data = cyto_tidy_death, fct = LL.4(names = c("Slope","Lower Limit", "Upper Limit", "AC50" )))



summary(regress_cyto)

```

```{r}
#Compute 95% CI for my IC50
ED(regress_cyto, 50, interval = "delta")%>%
 knitr::kable()

plot(regress_cyto, xlab = "Concentration (μM)", ylab = "Death (% from control)", col = "red", main = "Dose Response Curve for Rotenone")
 
 
 modelFit(regress_cyto)
```

